const notes = [
	{ note: 'C', frequency: 261.63, type: 'white' },
	{ note: 'C#', frequency: 277.18, type: 'black', marginRight: 'mr-2' },
	{ note: 'D', frequency: 293.66, type: 'white' },
	{ note: 'D#', frequency: 311.13, type: 'black', marginRight: 'mr-2' },
	{ note: 'E', frequency: 329.63, type: 'white' },
	{ note: 'F', frequency: 349.23, type: 'white' },
	{ note: 'F#', frequency: 369.99, type: 'black', marginRight: 'mr-12' },
	{ note: 'G', frequency: 392.0, type: 'white' },
	{ note: 'G#', frequency: 415.3, type: 'black', marginRight: 'mr-2' },
	{ note: 'A', frequency: 440.0, type: 'white' },
	{ note: 'A#', frequency: 466.16, type: 'black', marginRight: 'mr-2' },
	{ note: 'B', frequency: 493.88, type: 'white' },
	{ note: 'C2', frequency: 523.25, type: 'white' },
	{ note: 'C#2', frequency: 554.37, type: 'black', marginRight: 'mr-12' },
	{ note: 'D2', frequency: 587.33, type: 'white' },
	{ note: 'D#2', frequency: 622.25, type: 'black', marginRight: 'mr-2' },
	{ note: 'E2', frequency: 659.26, type: 'white' },
	{ note: 'F2', frequency: 698.46, type: 'white' },
	{ note: 'F#2', frequency: 739.99, type: 'black', marginRight: 'mr-12' },
	{ note: 'G2', frequency: 783.99, type: 'white' },
	{ note: 'G#2', frequency: 830.61, type: 'black', marginRight: 'mr-2' },
	{ note: 'A2', frequency: 880.0, type: 'white' },
	{ note: 'A#2', frequency: 932.33, type: 'black', marginRight: 'mr-2' },
	{ note: 'B2', frequency: 987.77, type: 'white' },
	{ note: 'C3', frequency: 1046.5, type: 'white' },
];

export default notes;
