const quotes_fr = [
	"Même un homme sage a plus à craindre d'un idiot qu'un idiot d'un homme sage.",
	'Nous vivons sur une planète étrange et nul ne connaît les limites de la folie humaine.',
	"La mort n'est que le début de quelque chose de plus sombre.",
	"N'oublie jamais que le diable était un ange avant de tomber.",
	"L'obscurité ne peut pas chasser l'obscurité ; seule la lumière le peut.",
	"Il y a des choses pires que la mort, et l'une d'elles est de n'avoir jamais commencé à vivre.",
	'Dans chaque ombre, il y a une peur qui sommeille.',
	"Le silence est aussi profond que l'éternité; le discours, aussi superficiel que le temps.",
	"Le vrai monstre est l'homme qui se cache derrière un visage humain.",
	"Quand tu regardes longtemps dans l'abîme, l'abîme regarde aussi en toi.",
	"Toute la douleur, la terreur et la détresse sont éclipsées par le moment où l'homme réalise que le néant l'attend.",
	"Il n'y a rien de plus terrifiant que l'ignorance en action.",
	"La peur est l'ombre de la possibilité, aussi sombre et vide que l'espace lui-même.",
	"Certains mystères ne doivent jamais être révélés, car la vérité derrière eux peut détruire l'âme.",
	"La folie est comme la gravité, il suffit d'une petite poussée.",
	'Chaque homme est un labyrinthe de secrets, certains trop sombres pour être dévoilés.',
	"Le cauchemar commence lorsqu'on se réveille et que la réalité est pire que le rêve.",
	'Même dans le rire le cœur peut se serrer et la joie se transformer en désespoir.',
	"La nuit est le miroir de l'âme noire, un abysse où se cachent nos peurs les plus profondes.",
	"Le plus grand horreur est celle qui ne montre rien, mais laisse tout à l'imagination.",
	'Les murmures du passé hantent toujours ceux qui écoutent trop attentivement.',
	"Le visage d'un homme peut cacher un monstre intérieur, attendant son moment pour se libérer.",
	'Les ombres sont les témoins silencieux de nos pires cauchemars.',
	"Il n'y a rien de plus terrifiant que l'esprit d'un homme corrompu par la vengeance.",
	'La solitude est le berceau des pensées les plus sombres.',
	'Le désespoir est le seul véritable éternel, toujours prêt à consumer les âmes perdues.',
	"Le murmure du vent est parfois un cri pour ceux qui ont entendu les secrets de l'ombre.",
	'Une conscience coupable est souvent un monstre vivant en nous.',
	"Il y a des regards qui peuvent consumer l'âme, laissant derrière eux que cendres et désolation.",
	"Le silence d'une pièce vide est parfois plus assourdissant que le plus bruyant des orages.",
];

module.exports = quotes_fr;
