const quotes_en = [
	'Even a wise man has more to fear from an idiot than an idiot from a wise man.',
	'We live on a strange planet, and none knows the limits of human madness.',
	'Death is but the doorway to something darker.',
	'Never forget that the devil was an angel before he fell.',
	'Darkness cannot drive out darkness; only light can do that.',
	'There are things worse than death, and one of them is never having begun to live.',
	'In every shadow, there lurks a fear.',
	'Silence is as deep as eternity; speech as shallow as time.',
	'The true monster is the man who hides behind a human face.',
	'When you gaze long into an abyss, the abyss also gazes into you.',
	'All pain, terror, and distress are eclipsed by the moment when man realizes that nothingness awaits him.',
	'There is nothing more terrifying than ignorance in action.',
	'Fear is the shadow of possibility, as dark and empty as space itself.',
	'Some mysteries should never be revealed, for the truth behind them can destroy the soul.',
	'Madness is like gravity, all it takes is a little push.',
	'Every man is a labyrinth of secrets, some too dark to be revealed.',
	'The nightmare begins when you wake up to a reality worse than any dream.',
	'Even in laughter the heart may ache, and joy may end in grief.',
	'The night is the mirror of the black soul, an abyss where our deepest fears hide.',
	'The greatest horror is that which shows nothing, leaving everything to the imagination.',
	'The whispers of the past always haunt those who listen too closely.',
	"A man's face can hide an inner monster, waiting for its moment to be released.",
	'Shadows are the silent witnesses of our worst nightmares.',
	'There is nothing more terrifying than the mind of a man corrupted by vengeance.',
	'Loneliness is the cradle of the darkest thoughts.',
	'Despair is the only true eternal, always ready to consume lost souls.',
	'The whisper of the wind is sometimes a scream for those who have heard the secrets of the shadows.',
	'A guilty conscience is often a living monster within us.',
	'There are glances that can consume the soul, leaving behind nothing but ashes and desolation.',
	'The silence of an empty room is sometimes more deafening than the loudest of storms.',
];

module.exports = quotes_en;
